import streamlit as st
import pandas as pd

from core.scoring import calculate_risk, risk_level, dimension_contributions
from core.scenarios import generate_scenarios
from data.sample_data import COUNTRIES, RELATIONSHIPS

st.set_page_config(page_title="GeoIntel AI", page_icon="🌍", layout="wide")

st.title("🌍 GeoIntel AI")
st.caption("Geopolitical Intelligence & Risk Analysis — V1 Prototype")

st.warning(
    "Prototype notice: scores in this V1 are demonstration values, not real-time "
    "forecasts or claims about the probability of armed conflict."
)

with st.sidebar:
    st.header("Analysis")
    country_a = st.selectbox("Country A", list(COUNTRIES.keys()), index=0)
    country_b = st.selectbox("Country B", list(COUNTRIES.keys()), index=1)

    if country_a == country_b:
        st.error("Please select two different countries.")
        st.stop()

    st.divider()
    st.subheader("Methodology")
    st.write("Security 25%")
    st.write("Political 15%")
    st.write("Diplomatic 15%")
    st.write("Economic 15%")
    st.write("Social 10%")
    st.write("Strategic 20%")

scores_a = COUNTRIES[country_a]
scores_b = COUNTRIES[country_b]

# Pair score: mean of country-level structural risks plus relationship modifiers.
base_scores = {
    k: round((scores_a[k] + scores_b[k]) / 2, 1)
    for k in scores_a
}
relationship = RELATIONSHIPS.get(
    tuple(sorted((country_a, country_b))),
    {"type": "NO_REGISTERED_RELATIONSHIP", "modifier": 0, "description": "No relationship data in the demo dataset."}
)

pair_scores = base_scores.copy()
pair_scores["diplomatic"] = max(
    0, min(100, pair_scores["diplomatic"] + relationship["modifier"])
)
pair_scores["security"] = max(
    0, min(100, pair_scores["security"] + relationship["modifier"] * 0.7)
)

overall = calculate_risk(pair_scores)
level = risk_level(overall)

st.subheader(f"{country_a} 🇺🇳 ↔ {country_b} 🇺🇳")

c1, c2, c3, c4 = st.columns(4)
c1.metric("Overall Risk", f"{overall}/100")
c2.metric("Risk Level", level)
c3.metric("Relationship", relationship["type"].replace("_", " ").title())
c4.metric("Model Version", "V1")

st.divider()

st.subheader("Risk Dimensions")
df = pd.DataFrame(
    [{"Dimension": k.title(), "Score": v} for k, v in pair_scores.items()]
)
st.dataframe(df, use_container_width=True, hide_index=True)

for dimension, score in pair_scores.items():
    st.write(f"**{dimension.title()} — {score}/100**")
    st.progress(int(score))

st.divider()

st.subheader("Relationship Assessment")
st.write(relationship["description"])

contrib = dimension_contributions(pair_scores)
contrib_df = pd.DataFrame(
    [{"Dimension": k.title(), "Weighted Contribution": v} for k, v in contrib.items()]
).sort_values("Weighted Contribution", ascending=False)
st.dataframe(contrib_df, use_container_width=True, hide_index=True)

st.divider()

st.subheader("Scenario Analysis")
scenarios = generate_scenarios(overall, relationship)

for scenario in scenarios:
    with st.expander(f"{scenario['name']} — {scenario['probability']}%"):
        st.write(scenario["description"])
        st.write(f"**Impact:** {scenario['impact']}/100")
        st.write(f"**Early indicators:** {', '.join(scenario['indicators'])}")

st.divider()

st.subheader("Analytical Guardrails")
st.markdown(
    """
- **Risk score ≠ event probability.** A 70/100 risk score does not mean a 70% chance of war.
- Scores are generated by a transparent weighted model.
- V1 uses demonstration data; real-world data ingestion is a later module.
- Forecasts should always include uncertainty, evidence, and alternative explanations.
"""
)

st.caption("GeoIntel AI V1 • Built as an extensible research prototype")
